Make `gem5` directory load as a package.
Add an empty __init__.py file so that python recognizes `gem5` as a
package. Otherwise it uses a namespace loader which does not provide
the `__file__` attribute needed by `inspect.getfile()`.

Error produced on python 3.10 without this patch:

    In [2]: import simulator
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    Cell In[2], line 1
    ----> 1 import simulator

    File ~/src/pie/gem5/simulator.py:27
         24 import subprocess
         25 import shlex
    ---> 27 GEM5_DIR_PATH=os.path.dirname(inspect.getfile(gem5))
         30 DOCKERFILE_TEMPLATE = """
         31 FROM alexshypula/gem5-skylake:api
         32
       (...)
         41
         42 """
         44 import logging

    File ~/opt/anaconda3/envs/pie/lib/python3.10/inspect.py:778, in getfile(object)
        776     if getattr(object, '__file__', None):
        777         return object.__file__
    --> 778     raise TypeError('{!r} is a built-in module'.format(object))
        779 if isclass(object):
        780     if hasattr(object, '__module__'):

    TypeError: <module 'gem5' (<_frozen_importlib_external._NamespaceLoader object at 0x7fce11f49930>)> is a built-in module